### ISSUE TITLE
Issue with yaml

### ISSUE THREAD

**Issue by flber** [heiswayi/thinkspace#42]
My fork is throwing a pages build error
`There was a YAML syntax error on line 3 column 11 in <unknown>: mapping values are not allowed in this context.`
I think this is refering to .travis.yml, but I'm not sure what's wrong. Here's the file
```
language: ruby
rvm: 
  - 2.6.0

before_script:
  - chmod +x ./script/cibuild.sh

script: ./script/cibuild.sh

# branch whitelist, only for Github pages
# https://jekyllrb.com/docs/continuous-integration/travis-ci/
branches:
  only:
  - master
  - gh-pages # test gh-pages branch
  - /pages-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speed up html-proofer install

sudo: false # route build to the container-based infrastructure for faster build

cache: bundler # caching bundler gem packages will speed up build

#before_install:
#  - gem update --system
#  - gem install bundler -v '< 2'
```

Any help would be much appreciated
